### ISSUE TITLE
Metabase exposures cause dbt to crash when referencing existing questions / variables because of jinja interpolation

### ISSUE THREAD

**Issue by Startouf** [gouline/dbt-metabase#148]
This happens when referencing other metabase questions in metabase

In the metabase exposures yml here is an extract of a problematic line

```yaml
exposures:
  - name: my_viz
    description: "### Visualization: Table\n\nSee https://example.com/xx\n\
      \n#### Query\n\n```\nwith \nappointments as (\n  select * FROM `xxxx.fct_appointments`\
      \ \n),\nusers as (\n  select * from {{#161}}\n  where last_active_at_cache >\
      \ timestamp_sub(current_timestamp, interval 365 DAY)\n),\napts as (\n  SELECT\
```

I believe dbt tries to interpolate the metabase question references as jinja expression, thus causing problems

```
jinja2.exceptions.TemplateSyntaxError: unexpected char '#' at 276
  line 13
    select * from {{#161}}
```

This is likely to cause problems with every metabase custom variable/reference wrapped under `{{}}`

Is there a way to either post-process the exposures.yml to escape those characters, or find a way to disable dbt jinja interpolation for metabase exposures ?
