### ISSUE TITLE
Ability to manage additional table metadata via DTB documentation

### ISSUE THREAD

**Issue by bulatyapparov** [gouline/dbt-metabase#240]
Table fields:

- Why this table is interesting
- Things to be aware of about this table

**Comment by bulatyapparov** [comment]
Found how to do this in this example: 

```yml
- name: model_name
  meta:
    metabase.display_name: another_model_name
    metabase.visibility_type: normal
    metabase.points_of_interest: Relevant records.
    metabase.caveats: Sensitive information about users.
```
