### ISSUE TITLE
Auto-Create Metabase Questions from dbt Models

### ISSUE THREAD

**Issue by korbash** [gouline/dbt-metabase#255]
# Auto-Create Metabase Questions from dbt Models

Creating SQL queries with multiple filters can be challenging. One of the most useful types of filters in Metabase is the [Field Filters](https://www.metabase.com/learn/sql-questions/field-filters). Interestingly, it's possible to integrate these filters directly from dbt models!

We can enhance the `schema.yml` file by adding filter features to columns intended to be used as filters. Here's an example of how to define these attributes in the metadata section:

```yaml
models:
  - name: orders
    columns:
      - name: order_date
        meta:
          metabase.filter:
            base-type: "type/Date"
            widget-type: "date/range"
```
To utilize these filters in the dbt models that are to be transformed into Metabase queries, reference the column in your model as follows:

```sql
WHERE '__filter__.<model_name>.<column_name>' = '__filter__.<model_name>.<column_name>'
```
After this setup, the dbt-metabase tool can automatically generate Metabase questions using the information from the `manifest.json` and the compiled models code.
