### ISSUE TITLE
Add tag to exported exposures

### ISSUE THREAD

**Issue by andrenmo** [gouline/dbt-metabase#270]
It would be very useful to have the possibility of passing one (or more) tags as a parameter so that they can be placed within the exposures.

```
dbt-metabase exposures \
    --manifest-path target/manifest.json \
    --metabase-url https://metabase.example.com \
    --metabase-api-key mb_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX= \
    --output-path models/
    --tag metabase_exposure
```

That command could generate this exposure:

```
version: 2
exposures:
  - name: our_report_2024
    label: Our Report 2024
    tags: ['metabase_exposure']
    description: '...
```
