### ISSUE TITLE
Propagation of foreign keys

### ISSUE THREAD

**Issue by AlizaminJ** [gouline/dbt-metabase#288]
According to [docs](https://github.com/gouline/dbt-metabase?tab=readme-ov-file#foreign-keys), native relationship tests are enough to propagate foreign keys. But it does not work, and any idea what I might be doing wrong? Defining them using metatags works, but I will preferably go for native solution (as you suggest as well).

```
sources:
- name: my_schema
    database: my_database
    tables:
      - name: searches
        columns:
          - name: id
            description: Primary key
            data_tests:
              - unique
              - not_null
          - name: term_id
            data_tests:
              - not_null
              - relationships:
                  to: source('my_schema', 'search_terms')
                  field: id
      - name: search_terms
        columns:
          - name: id
   ```
and I export my models with model_filter
```
c.export_models(
            metabase_database=METABASE_DATABASE,
            model_filter=Filter(include=["searches", "search_terms"]),
)
```

Great project, very much appreciated how much effort you have put into it!

EDIT: As far as I see it supports only [refs-relations](https://github.com/gouline/dbt-metabase/blob/master/dbtmetabase/manifest.py#L185) for now but not `sources`?
