### ISSUE TITLE
Multiple schemas in project

### ISSUE THREAD

**Issue by dubravcik** [gouline/dbt-metabase#3]
We are using multiple schemas specified in dbt_project.yml. It would be great if dbt-metabase follows the schema settings and does not send everything to the schema from the command line.

```
models:
  my_project:
    marketing:
      schema: marketing
    product:
      schema: product
    events:
      schema: events
```

thanks @gouline :)
