### ISSUE TITLE
Support `settings` in /api/field payload

### ISSUE THREAD

**Issue by ameier38** [gouline/dbt-metabase#317]
TLDR; Allow `metabase.settings` to be defined in dbt:
```yaml
      - name: gross_purchase_amount_processed
        meta:
          metabase.semantic_type: type/Currency
          metabase.settings:
            currency: USD
```

I have tables that are in both MXN and USD, and it would be great to be able to specify the currency of each field. Right now if I set the semantic type to type/Currency, then it just uses the default currency (which is MXN in our Metabase). I can manually change the currency of the field but it would be great to be able to define this in dbt.

For example, if I change this field to USD.

![Image](https://github.com/user-attachments/assets/21239038-c2c2-46ee-939e-8891e5ea6287)

Then the api call to /api/field/{id} has the payload:
```json
{
    "settings": {
        "currency": "USD"
    }
}
```

Let me know if you would like me to create a PR.

Also, thanks for creating and maintaining this project!
